# Übungsblatt 00

Dieser Code importiert zwei Bibliotheken: [PyTorch](https://pytorch.org/) und [Numpy](https://numpy.org/). PyTorch ist eine Bibliothek für maschinelles Lernen und die Deep Learning Bibliothek der Wahl in unserer Vorlesung. Numpy ist eine Bibliothek für wissenschaftliche Berechnung und implementiert viele der gängigen Algorithmen für Lineare Algebra.

**Aufgabe**: Führen Sie diese Zelle einmal zu Beginn der Übung aus damit die Bibliotheken importiert werden.

In [198]:
import torch
import numpy as np

# Aufgabe 4

Das zentrale Objekt das von den meisten Operationen in PyTorch verwendet wird sind Instanzen der $\texttt{torch.Tensor}$ Klasse. Die [Dokumentation](https://pytorch.org/docs/stable/tensors.html#torch.Tensor) beschreibt ein Tensor-Objekt als "eine mehrdimensionale Matrix, die Elemente eines einzigen Datentyps enthält." Die folgenden Aufgaben werden Sie mit dem Erstellen, dem Auslesen wichtiger Eigenschaften und dem Modifizieren von Tensorobjekten vertraut machen.

### Dimension, Form und Datentyp

Die zu den wichtigsten Attributen der Tensor Klasse gehört die Anzahl an Dimensionen $\texttt{torch.Tensor.dim()}$, die Form des Tensors $\texttt{torch.Tensor.shape}$ und der Datentyp der Einträgen $\texttt{torch.Tensor.dtype}$. 

**Aufgabe**: Gebe Sie die [Dimension](https://pytorch.org/docs/stable/generated/torch.Tensor.dim.html), die [Form](https://pytorch.org/docs/stable/generated/torch.Tensor.size.html) und den [Datentyp](https://pytorch.org/docs/stable/tensor_attributes.html?highlight=dtype#torch.torch.dtype) der Einträge des Tensors $\texttt{th\_tensor}$ aus.

In [199]:
th_tensor = torch.tensor([[1.0], [2.0], [3.0]])
# Begin eurer Lösung:
print(
    f"Dimension: {th_tensor.dim()}, Shape: {th_tensor.shape}, Datatype: {th_tensor.dtype}"
)

Dimension: 2, Shape: torch.Size([3, 1]), Datatype: torch.float32


## Zugriff und Manipulation von Tensoreinträgen

### Zugriff und Manipulation mit Slices

In Python können wir auf das i-te Element einer Liste $\texttt{L}$ mit $\texttt{L[i]}$ zugreifen. Hier sind auch negative Indices erlaubt wobei $-1$ dem Index des letzten Elements der Liste entspricht, $-2$ dem Index des vorletzten Elements, usw. Falls wir nicht nur auf einzelne Elemente sondern auf eine Teilliste zugreifen wollen erlaubt Python dies mit Hilfe von ``Slices''. Einen (strided) Slice einer Liste erhält man mit $\texttt{L[begin:end:step]}$.

PyTorch verallgemeinert diese Konzepte auf $n$-dimensionale Tensoren. Sei nun $\texttt{T}$ ein Tensor mit 3 Dimensionen und der Form $(d_1,d_2,d_3)$. Einfacher Zugriff $\texttt{T[i]}$ gibt in diesem Beispiel die i-te Matrix mit Größe $d_2$ x $d_3$ als torch.Tensor zurück. Wenn wir nun auf den Eintrag $(j,k)$ in dieser Matrix zugreifen wollen so ist dies möglich mit $\texttt{T[i,j,k]}$ wobei $\texttt{i,j,k}$ Integer sind und wir den k-ten Eintrag der j-ten Zeile in der i-ten Matrix als torch.Tensor erhalten.

Auch PyTorch unterstütz Slices allerdings ist es möglich einen Slice pro Dimension zu definieren, wobei wir für jede Dimension einen Slice mit dem obigen Syntax $\texttt{[start:stop:step]}$ verwenden. Schauen wir uns dazu einige Beispiele an:

 * $\texttt{T[2:5:1]}$ gibt eine Tensor zurück, der die Matrizen mit Index 2 bis 4 enthält. Dieser Ausdruck kann auch verkürzt werden zu $\texttt{T[2:5]}$.
 * $\texttt{T[0:d\_1:2]}$ gibt eine Tensor zurück, die jede Matrix mit geradem Index enthält. Dieser Ausdruck kann auch verkürzt werden zu $\texttt{T[::2]}$.
 * $\texttt{T[::-1]}$ gibt eine Tensor zurück, der alle Matrizen enthält allerdings wurde ihre Reihenfolge umgekehrt.
 * $\texttt{T[2:5, 0:d\_2:1, 0:2:1]}$ gibt eine Tensor zurück, der nur die ersten zwei Spalten der Matrizen mit Index 2 bis 4 enthält. Dieser Ausdruck kann auch verkürzt werden zu $\texttt{T[2:5,:,:2]}$.

Für einen n-dimensionalen Tensor $\texttt{T}$ der Größe $d_1$ x $d_2$ x ... x $d_n$ ist die allgemeine Form der Slices dementsprechend $\texttt{T[}b_1:e_1:s_1,b_2:e_2,s_2, ..., b_n:e_n:s_n\texttt{]}$ wobei $b_i, e_i \in [0:d_i-1]$ mit $b_i < e_i$ und $s_i \in \mathbb{Z}$. Wenn $s_i = 0$ oder $e_i = d_i-1$ müssen wir diese nicht explizit angeben und sollte $s_i = 1$ gelten können wir $s_i$  und den zweiten Doppelpunkt weglassen.


**Aufgabe**: Ihre Aufgabe ist mit Hilfe Ihres neuen Wissens über Slicing folgende Einträge des  $\texttt{th\_batched\_matrices}$ auszugeben:
1. Geben Sie das erste und das letzte Element des Tensors aus.
2. Geben Sie die erste und die zweite Matrix des Tensors aus.
3. Geben Sie die obere linke 2x2-Untermatrix jeder Matrix des Tensors aus.
4. Geben Sie die dritte Spalte jeder Matrix des Tensors aus.

In [200]:
th_batched_matrices = torch.arange(1, 91).reshape([10, 3, 3])

# Begin eurer Lösung:
print("Erstes Element des Tensors:", th_batched_matrices[0, 0, 0])
print("Letztes Element des Tensors:", th_batched_matrices[-1, -1, -1])

print("Erste und zweite Matrix des Tensors:", th_batched_matrices[:2])

print(
    "Obere linke 2x2-Untermatrix jeder Matrix des Tensors:",
    th_batched_matrices[:, :2, :2],
)

print("Dritte Spalte jeder Matrix des Tensors:", th_batched_matrices[:, :, 2:])


Erstes Element des Tensors: tensor(1)
Letztes Element des Tensors: tensor(90)
Erste und zweite Matrix des Tensors: tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
Obere linke 2x2-Untermatrix jeder Matrix des Tensors: tensor([[[ 1,  2],
         [ 4,  5]],

        [[10, 11],
         [13, 14]],

        [[19, 20],
         [22, 23]],

        [[28, 29],
         [31, 32]],

        [[37, 38],
         [40, 41]],

        [[46, 47],
         [49, 50]],

        [[55, 56],
         [58, 59]],

        [[64, 65],
         [67, 68]],

        [[73, 74],
         [76, 77]],

        [[82, 83],
         [85, 86]]])
Dritte Spalte jeder Matrix des Tensors: tensor([[[ 3],
         [ 6],
         [ 9]],

        [[12],
         [15],
         [18]],

        [[21],
         [24],
         [27]],

        [[30],
         [33],
         [36]],

        [[39],
         [42],
         [45]],

        [[48],

### Boolean Array Indexing

Boolean Indexing ist eine Technik, um Elemente aus einem Tensor in PyTorch auszuwählen, die einer bestimmten Bedingung entsprechen. Dabei wird ein Tensor mit booleschen Werten (True oder False) verwendet, der die gleiche Form wie der ursprüngliche Tensor hat. Nur die Elemente, die an den Positionen True sind, werden ausgewählt. Ein kurzes Beispiel ist:

```python
    # Erstellen eines Tensors mit zufälligen Zahlen
    x = torch.randn(3, 4)

    # Erstellen eines booleschen Tensors mit der Bedingung x > 0
    mask = x > 0

    # Auswählen der Elemente aus x, die der Bedingung entsprechen
    y = x[mask]
```

**Aufgabe**: Verwenden Sie von Boolean Array Indexing um alle negativen Einträge in den Matrizen im Tensor $\texttt{th\_batched\_matrices}$ durch Nullen ersetzen. Geben Sie die fünfte und sechste Matrizen vor und nach dem Ändern der Einträge sowie die Form und den Datentyp der Einträge der bool Maske aus.

In [201]:
th_batched_matrices = torch.arange(-45, 45).reshape([10, 3, 3])

# Begin eurer Lösung:
print("Matrizen 5 und 6 vor dem Ändern:", th_batched_matrices[4:6])
mask = th_batched_matrices >= 0
print("Form und Datentyp der bool-Maske:", mask.shape, mask.dtype)
th_batched_matrices = th_batched_matrices * mask
print("Matrizen 5 und 6 nach dem Ändern:", th_batched_matrices[4:6])

Matrizen 5 und 6 vor dem Ändern: tensor([[[-9, -8, -7],
         [-6, -5, -4],
         [-3, -2, -1]],

        [[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]]])
Form und Datentyp der bool-Maske: torch.Size([10, 3, 3]) torch.bool
Matrizen 5 und 6 nach dem Ändern: tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])


### Integer Array Indexing

Um auf Einträge eines Pytorch Tensors mit Hilfe einer Liste von Indices zuzugreifen, kann man die Liste als Index für den Tensor verwenden. Dies gibt einen neuen Tensor zurück, der die Elemente an den angegebenen Indices enthält. Dies funktioniert sowohl für eindimensionale als auch für mehrdimensionale Tensoren. 

**Aufgabe**: Im Beispiel wird ein dreidimensionaler Tensor mit 10 Matrizen der Größe 3x3 erstellt und dann mit einer Liste von Indices [1, 2, 3, 5, 8] indiziert. Das Ergebnis ist ein neuer Tensor mit 5 Matrizen der Größe 3x3, die den Einträgen an den geraden Indices des ursprünglichen Tensors entsprechen.

In [202]:
th_batched_matrices = torch.arange(-45, 45).reshape([10, 3, 3])

# Begin eurer Lösung:
indices = [1, 2, 3, 5, 8]
sliced_tensor = th_batched_matrices[indices]
print(sliced_tensor)
print(sliced_tensor.shape)

tensor([[[-36, -35, -34],
         [-33, -32, -31],
         [-30, -29, -28]],

        [[-27, -26, -25],
         [-24, -23, -22],
         [-21, -20, -19]],

        [[-18, -17, -16],
         [-15, -14, -13],
         [-12, -11, -10]],

        [[  0,   1,   2],
         [  3,   4,   5],
         [  6,   7,   8]],

        [[ 27,  28,  29],
         [ 30,  31,  32],
         [ 33,  34,  35]]])
torch.Size([5, 3, 3])


## Grundlegende Operationen

### Elementare Funktionen

Selbstverständlich unterstützt PyTorch elementare Operatoren $+,-,*,/$ (und noch einige weitere) zwischen mit zwei Tensoren der gleichen Größe oder einem Tensor und einem Skalar. In beiden Fällen handelt es sich um elementweise Operationen auf den Einträgen des Tensors. Um uns davon zu überzeugen, dass sich die Operatoren verhalten wie wir erwarten bearbeiten Sie bitte die folgende Aufgabe:

**Aufgabe**:  Führen Sie die folgenden Operationen durch und geben Sie den resultierenden Tensor aus:

1. Die Summe aus $\texttt{th\_tensor1}$ und $\texttt{th\_tensor2}$ und $\texttt{th\_tensor1}$ und dem Skalar $\texttt{constant}$.
2. Die Differenz zwischen $\texttt{th\_tensor1}$ und $\texttt{th\_tensor2}$ und $\texttt{th\_tensor1}$ und dem Skalar $\texttt{constant}$.
3. Das Produkt zwischen $\texttt{th\_tensor1}$ und $\texttt{th\_tensor2}$ und $\texttt{th\_tensor1}$ und dem Skalar $\texttt{constant}$.
4. Der Quotient zwischen $\texttt{th\_tensor1}$ und $\texttt{th\_tensor2}$ und $\texttt{th\_tensor1}$ und dem Skalar $\texttt{constant}$. 

In [203]:
th_tensor1 = torch.ones([2, 2])
th_tensor2 = torch.full([2, 2], 2)
constant = 10.0

# Begin eurer Lösung
sum_1 = th_tensor1 + th_tensor2 + th_tensor1 + constant
print(sum_1)
difference_2 = th_tensor1 - th_tensor2 - th_tensor1 - constant
print(difference_2)
product_3 = th_tensor1 * th_tensor2 * th_tensor1 * constant
print(product_3)
quotient_4 = th_tensor1 / th_tensor2 / th_tensor1 / constant
print(quotient_4)

tensor([[14., 14.],
        [14., 14.]])
tensor([[-12., -12.],
        [-12., -12.]])
tensor([[20., 20.],
        [20., 20.]])
tensor([[0.0500, 0.0500],
        [0.0500, 0.0500]])


## Konstruktionen von Tensoren

### Manuelles Erzeugen von Tensoren

Es gibt eine Vielzahl von Möglichkeiten um einen Tensor selbst zu erzeugen. Hier wollen wir uns nur vier gängige Methoden anschauen:

 * [torch.from_numpy()](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - Diese Methode erzeugt einen Tensor aus einem bestehenden Numpy-Array. Der Tensor teilt sich den Speicher mit dem Array, so dass Änderungen an einem sich auf das andere auswirken.
 * [torch.tensor()](https://pytorch.org/docs/stable/generated/torch.tensor.html) - Diese Methode erzeugt einen Tensor aus einer Numpy-Array, Liste oder einem Tupel von Werten. Der Tensor hat einen eigenen Speicher und ist unabhängig von der Eingabe.
 * [torch.rand()](https://pytorch.org/docs/stable/generated/torch.rand.html) - Diese Methode erzeugt einen Tensor mit zufälligen Werten aus einer gleichmäßigen Verteilung zwischen 0 und 1. Die Größe des Tensors muss als Argument angegeben werden.
 * [torch.randn()](https://pytorch.org/docs/stable/generated/torch.randn.html) - Diese Methode erzeugt einen Tensor mit zufälligen Werten aus einer Normalverteilung mit Mittelwert 0 und Standardabweichung 1. Die Größe des Tensors muss als Argument angegeben werden.

**Aufgabe**: Verwenden Sie die oben genannten Möglichkeiten wie folgt um Tensoren zu erstellen:

 1. Erzeugen Sie einen $\texttt{torch.Tensor}$ aus dem Numpy-Array $\texttt{np\_array}$, indem Sie die Funktion torch.from_numpy().
 2. Verwenden Sie torch.tensor() um einen Tensor zu erzeugen der die Einträge 1,2,3 hat.
 3. Erstellen Sie eine 2x2 Matrix als $\texttt{torch.Tensor}$, die mit gleichverteilen Werten zwischen 0 und 1 gefüllt ist.
 4. Erstellen Sie eine 2x2 Matrix als $\texttt{torch.Tensor}$, die mit normalverteilten Werten gefüllt ist

Geben Sie den resultierenden Tensor für jede der vier Teilaufgaben aus.

In [204]:
np_array = np.array([1.0, 2.0, 3.0])

# Begin eurer Lösung:
np_tensor_1 = torch.from_numpy(np_array)
print(np_tensor_1)

np_tensor_2 = torch.tensor([1, 2, 3])
print(np_tensor_2)

rand_tensor = torch.rand(2, 2)
print(rand_tensor)

randn_tensor = torch.randn(2, 2)
print(randn_tensor)

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3])
tensor([[0.0101, 0.5532],
        [0.2507, 0.7403]])
tensor([[0.4002, 0.1107],
        [1.1472, 1.9531]])


### Konstruktion mit Concatination und Stack.

Die Funktion [torch.cat()](https://pytorch.org/docs/stable/generated/torch.cat.html) dient dazu, mehrere Tensoren entlang einer bestimmten Dimension zu einem einzigen Tensor zu verbinden. Die Tensoren müssen die gleiche Form haben, außer in der Dimension, entlang derer sie verbunden werden. Die Funktion nimmt als Argumente eine Sequenz von Tensoren und die Dimension, entlang derer sie verbunden werden sollen. Die Funktion gibt einen neuen Tensor zurück, der die Elemente aller Eingabetensoren enthält.

Die Funktion [torch.stack()](https://pytorch.org/docs/stable/generated/torch.stack.html) erlaubt es, mehrere Tensoren entlang einer neuen Dimension zu stapeln. Dabei müssen alle Tensoren die gleiche Größe und den gleichen Datentyp haben. Die neue Dimension wird an der angegebenen Position eingefügt, die standardmäßig 0 ist. Das Ergebnis ist ein Tensor mit einer zusätzlichen Dimension, deren Größe der Anzahl der gestapelten Tensoren entspricht.

**Aufgabe**: Gegeben sind drei Matrizen $\texttt{th\_matrix1}$, $\texttt{th\_matrix2}$ und $\texttt{th\_matrix3}$ mit der gleichen Anzahl von Spalten, aber unterschiedlichen Anzahlen von Zeilen. Schreiben Sie ein Programm, das die folgenden Operationen ausführt:

- Verbinden Sie die drei Matrizen entlang der Zeilenachse zu einer neuen Matrix und geben Sie deren Form aus.
- Verbinden Sie die drei Matrizen entlang der Spaltenachse zu einer neuen Matrix und geben Sie deren Form aus.
- Stapeln Sie die drei Matrizen entlang der ersten Dimension zu einem neuen Tensor und geben Sie dessen Form aus.
- Stapeln Sie die drei Matrizen entlang der zweiten Dimension zu einem neuen Tensor und geben Sie dessen Form aus.

In [205]:
th_matrix1 = torch.rand([5, 6])
th_matrix2 = torch.rand([5, 6])
th_matrix3 = torch.rand([5, 6])

# Begin eurer Lösung
tensor_cat_1 = torch.cat((th_matrix1, th_matrix2, th_matrix3))
print(tensor_cat_1.shape)
tensor_cat_2 = torch.cat((th_matrix1, th_matrix2, th_matrix3), dim=1)
print(tensor_cat_2.shape)
tensor_stack_1 = torch.stack((th_matrix1, th_matrix2, th_matrix3))
print(tensor_stack_1.shape)
tensor_stack_2 = torch.stack((th_matrix1, th_matrix2, th_matrix3), dim=1)
print(tensor_stack_2.shape)

torch.Size([15, 6])
torch.Size([5, 18])
torch.Size([3, 5, 6])
torch.Size([5, 3, 6])


## Datentypkonvertierung

Die Einträge eines Tensors haben einen bestimmten Datentyp, wie z.B. torch.float32, torch.uint8 oder torch.bool. Der Datentyp der Einträge kann großen Einfluss auf die Performance haben, da er bestimmt, wie viel Speicherplatz ein Tensor benötigt und welche Operationen auf ihm ausgeführt werden können. Nicht alle Operationen sind für alle Datentypen implementiert.

Die Typkonvertierung der Einträge eines Tensors wird mit der Funktion [torch.Tensor.to()](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) durchgeführt. Diese Methode nimmt einen den neuen Datentyp als Argument und gibt einen neuen Tensor dessen Einträge den gewünschten Datentyp haben zurück. Zum Beispiel kann man einen Tensor mit float-Einträgen in einen Tensor mit int-Einträgen konvertieren, indem man .to(torch.int) aufruft.

Datentypenkonvertierung in Pytorch wird häufig gebraucht beim Laden von Datensätzen, da die Daten oft in verschiedenen Formaten vorliegen. Zum Beispiel können Bilder als uint8-Werte gespeichert sein, die zwischen 0 und 255 liegen. Um diese Daten für das Training eines neuronalen Netzes zu verwenden, bietet es sich an dass wir sie in float-Werte konvertieren, die zwischen 0 und 1 liegen. Dies kann man mit der Methode $\texttt{.to(torch.float32)}$ und einer Division durch 255 erreichen.

**Aufgabe**: Geben Sie den Datentyp der Einträge der Tensoren $\texttt{np\_tensor}$ und $\texttt{th\_tensor}$ aus. Konvertieren Sie die Datentype der Tensoren zu $\texttt{torch.float32}$ und geben Sie den Datentypen erneut aus.

In [206]:
np_array = np.array([1.0, 2.0, 3.0])
np_tensor = torch.from_numpy(np_array)
th_tensor = torch.tensor([1.0, 2.0, 3.0])
# Begin eurer Lösung:
print("Datentyp von np_tensor:", np_tensor.dtype)
print("Datentyp von th_tensor:", th_tensor.dtype)

np_tensor = np_tensor.to(torch.float32)
print("Datentyp von np_tensor:", np_tensor.dtype)

Datentyp von np_tensor: torch.float64
Datentyp von th_tensor: torch.float32
Datentyp von np_tensor: torch.float32


## Grundlegende Funktionen

### Elementweise Funktionen

Elementweise Funktionen werden auf jedes Element eines Tensors angewendet werden, ohne die Form oder Dimension des Tensors zu ändern. Einige Beispiele für elementweise Funktionen sind [abs](https://pytorch.org/docs/stable/generated/torch.abs.html), [cos](https://pytorch.org/docs/stable/generated/torch.cos.html), [sin](https://pytorch.org/docs/stable/generated/torch.sin.html), [exp](https://pytorch.org/docs/stable/generated/torch.exp.html), [log](https://pytorch.org/docs/stable/generated/torch.log.html) usw. Um eine elementweise Funktion auf einen Tensor anzuwenden, muss man nur die Funktion mit dem Tensor als Argument aufrufen.

**Aufgabe**: Berechnen Sie den Betrag der Werte im Tensor $\texttt{th\_tensor}$ und geben Sie Werte in dem resultierenden Tensor aus.

In [207]:
th_tensor = torch.full([3], -2.0)

# Begin eurer Lösung:
abs_th_tensor = abs(th_tensor)
print(abs_th_tensor)

tensor([2., 2., 2.])


### Dimensionen als Argument

Einige Funktionen in PyTorch akzeptieren Dimensionen als optionales Argument, um eine Operation entlang einer Achsen oder mehreren Achsen eines Tensors auszuführen. Zum Beispiel kann die Funktion [torch.amin](https://pytorch.org/docs/stable/generated/torch.amin.html)/[torch.amax](https://pytorch.org/docs/stable/generated/torch.amax.html) einen Tensor als Eingabe nehmen und das Minimum bzw. Maximum entlang einer oder mehrerer Dimensionen zurückgeben. Die Funktion [torch.sum](https://pytorch.org/docs/stable/generated/torch.sum.html) kann einen Tensor als Eingabe nehmen und die Summe entlang einer oder mehrerer Dimensionen zurückgeben. Die Dimensionen werden als Liste oder Tupel von ganzen Zahlen angegeben, die die Indizes der Achsen darstellen, über die die Operation ausgeführt werden soll. Hier ist ein Beispiel:

```python
torch.sum(th_tensor, dim=[0,2])
```

**Aufgabe**: 
* Verwenden Sie amin und geben Sie den kleinsten und größten Wert des Tensor $\texttt{th\_tensor}$ aus.
* Verwenden Sie amin und geben Sie den kleinsten und größten Wert des Tensors $\texttt{th\_tensor}$ über die letzten zwei Achsen aus.
* Verwenden Sie sum und geben Sie die Summe aller Einträge des Tensors $\texttt{th\_tensor}$ aus.
* Verwenden Sie sum um die Summe der Einträge des Tensors $\texttt{th\_tensor}$ über die letzten zwei Achsen zu berechnen und auszugeben.

In [208]:
th_tensor = torch.linspace(-9.0, 9.0, steps=20).reshape(5, 2, 2)

# Begin eurer Lösung
min_th_tensor_1 = torch.amin(th_tensor)
max_th_tensor_1 = torch.amax(th_tensor)
print(f"Mindestwert des Tensors: {min_th_tensor_1}")
print(f"Maximalwert des Tensors: {max_th_tensor_1}")

min_th_tensor_2 = torch.amin(th_tensor, dim=[-2, -1])
max_th_tensor_2 = torch.amax(th_tensor, dim=[-2, -1])
print(f"Mindestwert des Tensors: {min_th_tensor_2}")
print(f"Maximalwert des Tensors: {max_th_tensor_2}")
sum_th_tensor_1 = torch.sum(th_tensor)
print(f"Summe aller Einträge des Tensors: {sum_th_tensor_1}")

sum_th_tensor_2 = torch.sum(th_tensor, dim=[-2, -1])
print(f"Summe der Einträge des Tensors über die letzten zwei Achsen: {sum_th_tensor_2}")


Mindestwert des Tensors: -9.0
Maximalwert des Tensors: 9.0
Mindestwert des Tensors: tensor([-9.0000, -5.2105, -1.4211,  2.3684,  6.1579])
Maximalwert des Tensors: tensor([-6.1579, -2.3684,  1.4211,  5.2105,  9.0000])
Summe aller Einträge des Tensors: -1.9073486328125e-06
Summe der Einträge des Tensors über die letzten zwei Achsen: tensor([-30.3158, -15.1579,   0.0000,  15.1579,  30.3158])


## Manipulation der Form eines Tensors

### Reshape/View

[torch.reshape](https://pytorch.org/docs/stable/generated/torch.reshape.html) und [torch.Tensor.view](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) sind Funktionen, die verwendet werden, um die Form eines Tensors zu ändern wobei die Anzahl der Einträge der neuen Form und alten Form gleich sein muss.

Die Funktion $\texttt{torch.reshape}$ gibt falls möglich eine eine "view" des ursprünglichen Tensors zurück und sonst eine Kopie des Tensors. Die Funktion $\texttt{torch.Tensor.view}$ gibt immer eine "view" des ursprünglichen Tensors zurück. Eine "view" eines Tensor ist eine Referenz auf den Speicherbereich des ursprünglichen Tensor die diesen aber in einer anderen Form darstellt.

**Aufgabe**: Geben Sie die Form des Tensors $\texttt{th\_tensor}$ aus. Ändern Sie die Form von $\texttt{th\_tensor}$ in eine $3$ x $3$ Matrix und geben Sie Form des neuen Tensors aus.

In [209]:
th_tensor = torch.arange(9)

# Begin eurer Lösung:
print(th_tensor.shape)
th_tensor = th_tensor.reshape((3, 3))
print(th_tensor.shape)


torch.Size([9])
torch.Size([3, 3])


### Transponieren von Tensoren

Das Transponieren ist eine Operation, die die Dimensionen eines Tensors vertauscht. Zum Beispiel wird ein Tensor der Form (2, 3) zu einem Tensor der Form (3, 2) transponiert. Das Transponieren kann mit der Funktion [torch.transpose](https://pytorch.org/docs/stable/generated/torch.transpose.html) durchgeführt werden, die einen "view" des Eingabetensors zurückgibt. Die Funktion erwartet einen Tensor so wie zwei Dimensionen die vertauscht werden sollen als Argument.


**Aufgabe**:
 * Geben Sie die Form von $\texttt{th\_matrix}$ aus, transponieren Sie die Matrix in eine $2$ x $4$ Matrix und geben Sie die Form des neuen Tensors aus.
 * Geben Sie die Form von $\texttt{th\_batched\_matrices}$ aus, transponieren Sie alle 10 Matrizen von $4$ x $2$ Matrizen in  $2$ x $4$ Matrizen mit einem Befehl und geben Sie die Form des neuen Tensors aus.


In [210]:
th_matrix = torch.rand([4, 2])
th_batched_matrices = torch.rand([10, 4, 2])

# Begin eurer Lösung:
print(th_matrix.shape)
th_matrix = th_matrix.transpose(dim0=0, dim1=1)
print(th_matrix.shape)

print(th_batched_matrices.shape)
th_batched_matrices = th_batched_matrices.transpose(dim0=1, dim1=2)
print(th_batched_matrices.shape)

torch.Size([4, 2])
torch.Size([2, 4])
torch.Size([10, 4, 2])
torch.Size([10, 2, 4])


## Broadcasting

Eine weiter nützliche Funktion von Tensoren, ist die Möglichkeit des [Boardcasting](https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics) von Operation. Broadcasting erlaubt es eine Operation auf Tensoren unterschiedlicher Größe anzuwenden ohne die Daten vorher zu kopieren wenn die Form der Tensoren folgende Bedingungen erfüllen:

+ Jeder Tensor hat mindestens eine Dimension.
+ Bei der Iteration über die Dimensionsgrößen, beginnend mit der letzten Dimension, müssen die Dimensionsgrößen entweder gleich sein, eine von ihnen ist 1 oder eine von ihnen existiert nicht.
    
Wenn diese Bedingungen erfüllt sind, wird die Operation elementweise entlang der unterschiedlichen Dimensionen angewendet. 

**Aufgabe**: In der nächsten Codezelle sind ein paar Beispiele für Broadcasting. Einige davon scheinen aber nicht zu funktionieren. Kommentieren Sie alle Beispiele aus die nicht funktionieren und beschreiben Sie in einem weiteren Kommentar kurz warum das Beispiel. Nehmen Sie dabei Bezug auf die obenstehenden Regeln für Broadcasting.



In [211]:
th_batched_matrices = torch.rand([10, 4, 2])
th_matrix = torch.rand([4, 2])

# Frist example
x = torch.ones(2, 3)  # shape (2, 3)
y = torch.randn(3)  # shape (3)
z = x + y  # add x and y using broadcasting
print(
    f"Shape of x: {x.shape}, shape of y {y.shape}, shape of the resulting tensor {z.shape}"
)

# Second example
# x = torch.ones(2, 3, 2)  # shape (2, 3, 2)
# y = torch.randn(2, 3)  # shape (2, 3)
# z = x + y  # add x and y using broadcasting
# print(
#     f"Shape of x: {x.shape}, shape of y {y.shape}, shape of the resulting tensor {z.shape}"
# )

# Does not work, because the last two dimensions do not follow the rules,
# as 3,2 and 2,3 are neither equal nor is one of them 1. So the broadcasting fails.

# Third example
x = torch.ones(2, 3, 4, 5)  # shape (2, 3, 4, 5)
y = torch.randn(3, 1, 1)  # shape (3, 1, 1)
z = x + y  # add them using broadcasting
print(
    f"Shape of x: {x.shape}, shape of y {y.shape}, shape of the resulting tensor {z.shape}"
)

# # Fourth example
# x = torch.ones(2, 3, 4, 5, 1)  # shape (2, 3, 4, 5, 1)
# y = torch.randn(2, 3, 1)  # shape (2, 3, 1)
# z = x + y  # add them using broadcasting
# print(
#     f"Shape of x: {x.shape}, shape of y {y.shape}, shape of the resulting tensor {z.shape}"
# )

# This does not work because the matching of the second last dimension fails, as 5,3 neither of which is one nor are they equal

Shape of x: torch.Size([2, 3]), shape of y torch.Size([3]), shape of the resulting tensor torch.Size([2, 3])
Shape of x: torch.Size([2, 3, 4, 5]), shape of y torch.Size([3, 1, 1]), shape of the resulting tensor torch.Size([2, 3, 4, 5])


### Singleton Dimensionen hinzufügen und entfernen

Um Broadcasting zu richtig zu nutzen ist es notwendig die Anzahl der Dimensionen kontrollieren zu können und ggf. zusätzliche "singleton" Dimensionen (Dimensionen deren Größe eins ist) hinzuzufügen oder entfernen zu können. Zusätzlich zu $\texttt{torch.reshape}$ und $\texttt{torch.Tensor.view}$ bietet PyTorch und noch zwei weiter Möglichkeiten "singleton" Dimensionen hinzufügen:

 1. [torch.unsqueeze()](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html) - fügt eine neue Dimension mit der Größe 1 an einer bestimmten Position hinzufügt. Die Funktion erwartet die Achse an der die Dimension eingefügt wird als Argument. Für einen Tensor $\texttt{T}$ mit Form $d_1$ x $d_2$ gibt $\texttt{T.unsqueeze(1)}$ einen Tensor zurück der eine zusätzliche Dimension zwischen $d_1$ und $d_2$ hat.
 2. $\texttt{None}$ - kann in der Indizierung eines Tensors verwendet werden um eine zusätzliche Dimension hinzufügen. Für einen Tensor $\texttt{T}$ mit Form $d_1$ x $d_2$ gibt $\texttt{T[:,None,:]}$ einen Tensor zurück der eine zusätzliche Dimension zwischen $d_1$ und $d_2$ hat.

Wenn wir "singleton" Dimensionen entfernen wollen bietet PyTorch uns folgende Möglichkeiten:

 1. [torch.squeeze()](https://pytorch.org/docs/stable/generated/torch.squeeze.html) - entfernt alle Dimensionen mit der Größe 1 aus einem Tensor falls keine Achse als Argument übergeben wird; wollen wir nur eine spezifische "singleton"-Dimension entfernen können wir ihren Index als Argument angeben. 
 2. Indizierung - kann ebenfalls verwendet werden um spezifische "singleton" Dimensionen zu entfernen. Für einen Tensor $\texttt{T}$ mit Form $d_1$ x 1 x $d_2$ gibt $\texttt{T[:,0,:]}$ einen Tensor mit Größe $d_1$ x $d_2$ zurück.

Auch zum Entfernen von "singleton" Dimensionen lassen sich natürlich torch.reshape oder torch.view verwenden.

**Aufgabe**: Verwenden Sie torch.squeeze und torch.unsqueeze um "singleton" Dimensionen zu x und y hinzufügen oder zu entfernen so dass $z = x+y$ berechnet werden kann. Geben Sie die Form des resultierenden Vektors aus.

In [212]:
x = torch.ones(2, 3, 4, 5, 1)  # shape (2, 3, 4, 5, 1)
y = torch.randn(1, 2, 3, 5)  # shape (2, 3, 1)

# Begin eurer Lösung:
x = x.squeeze()
y = y.squeeze(0).unsqueeze(2)
print(x.shape)
print(y.shape)

z = x + y
print(z.shape)

torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 1, 5])
torch.Size([2, 3, 4, 5])


## Matrix und Vektor Produkte

In PyTorch können wir fast alle Vektor/Matrix Produkte mit der Funktion [$\texttt{torch.matmul}$](https://pytorch.org/docs/stable/generated/torch.matmul.html) berechnen. Das Verhalten der Funktion ist dabei anhängig von der Dimension der Eingabetensoren und wird von der Dokumentation wie folgt beschrieben:

 + Wenn beide Tensoren 1-dimensional sind, wird das Skalarprodukt zurückgegeben.

 + Sind beide Argumente 2-dimensional, wird das Matrix-Matrix-Produkt zurückgegeben.

 + Ist das erste Argument eindimensional und das zweite Argument zweidimensional, wird seiner Dimension für die Zwecke der Matrixmultiplikation eine 1 vorangestellt. Nach der Matrixmultiplikation wird die vorangestellte Dimension wieder entfernt.

 + Ist das erste Argument 2-dimensional und das zweite Argument 1-dimensional, wird das Matrix-Vektor-Produkt zurückgegeben.
 
 + Wenn beide Argumente mindestens 1-dimensional sind und mindestens ein Argument N-dimensional ist (wobei N > 2 ist), wird eine Multiplikation einer gepackten Matrix zurückgegeben. Ist das erste Argument eindimensional, so wird seiner Dimension für die Zwecke der Multiplikation der gepackten Matrix eine 1 vorangestellt und danach entfernt. Ist das zweite Argument eindimensional, wird seiner Dimension eine 1 vorangestellt, um die Matrix zu multiplizieren, und danach entfernt. Die Funktion verwendet broadcasting entlang der "singleton" Dimensionen.

Der @-Operator ist äquivalent zu torch.matmul() und kann auf zwei Tensoren angewendet werden, die die gleichen Dimensionen haben oder broadcastbar sind.

**Aufgabe** Gegeben ist eine Matrix $A$ und Vektoren $v_1, ..., v_5$. Verwenden Sie Ihr neues Wissen über "singleton" Dimensionen und Broadcasting um mit je einem matmul-Aufruf folgende Berechnung dazuführen und das Ergebnis auszugeben:

1. Berechne das Skalarprodukt $\langle v_1, v_1 \rangle$
2. Berechne das Matrix/Vektor Produkt $A \cdot v$
3. Berechne das Matrix/Matrix Produkt $A^T \cdot A$
4. Berechne das Matrix/Matrix Produkt $A \cdot v_i$ für alle $i \in [1:5]$ mit nur einem matmul Aufruf.


In [213]:
th_batched_vectors = torch.arange(10, dtype=torch.float32).reshape(
    5, 2
)  # Vektoren v_1, ..., v_5 in einem Tensor
th_vector = th_batched_vectors[0]  # Vektor v_1 als seperater Tensor
th_matrix = torch.arange(8, dtype=torch.float32).reshape(4, 2)  # Matrix A

print(th_matrix.shape)
print(th_matrix.transpose(0,1).shape)
print(th_vector.shape)

# Begin euer Lösung:
solution_1 = th_vector @ th_vector
print(solution_1)

solution_2 = th_matrix @ th_vector
print(solution_2)

solution_3 = th_matrix.transpose(0,1) @ th_matrix
print(solution_3)

solution_4 = th_matrix @ th_batched_vectors.transpose(0,1)
print(solution_4)

print(th_batched_vectors.shape)

torch.Size([4, 2])
torch.Size([2, 4])
torch.Size([2])
tensor(1.)
tensor([1., 3., 5., 7.])
tensor([[56., 68.],
        [68., 84.]])
tensor([[  1.,   3.,   5.,   7.,   9.],
        [  3.,  13.,  23.,  33.,  43.],
        [  5.,  23.,  41.,  59.,  77.],
        [  7.,  33.,  59.,  85., 111.]])
torch.Size([5, 2])


## 